### ISSUE TITLE
Ignore certain directory from theme-check

### ISSUE THREAD

**Issue by theKhorshed** [Otto42/theme-check#103] opened 2015-12-14 10:39 UTC
Hi, I think it would be better if there have any option to exclude certain file or directory from theme-check. 

On development time we have node_modules, .git and many other dev dependency and errors from these directory distract to find errors from theme.

It would be really great if we get a way ignore these (like .gitignore).

Thanks for the great works.

**Comment by Otto42** [comment] 2015-12-14 22:09
Duplicate of #4 and #9.

**Closed by Otto42** 2015-12-14 22:09 UTC
Labels: duplicate
